name = "Schedule"
root_directory = "../testbench"

[make]
run_make = true
use_stdout = true

[submissions]
archive_filename = '../submissions.zip'
archive_type = "zip"
submission_type = "tar.gz"
languages = ["C"]
program = "schedule"
type = "executable"

[tests]
timeout = 30
# directory = '/home/gavinruane/Documents/Projects/csc453-grading/testbench/tests'
givens_directory = '/home/gavinruane/Documents/Fall2025/csc453_isa/projects/project1/project1_grading/givens'
