name = "Scheduler"
root_directory = "../testbench"

[make]
run_make = true
use_stdout = true

[submissions]
archive_filename = '../submissions.zip'
archive_type = "zip"
submission_type = "tar.gz"

[tests]
test_directory = '/Users/gavinruane/Documents/453example/schedule_tests'
